### ISSUE TITLE
Fix pwd() in Root Directory

### ISSUE THREAD

**Issue by JustinJiaDev** [JustinJiaDev/SwiftShell#3]
Currently, calling `pwd()` in the root directory will cause the program to crash.

**Comment by hooman96** [comment]
commands:
pwd()

cd()

cd("/")

pwd()

output:

SwiftShell $ pwd
/
SwiftShell $ cd /Users/hmohammadi
SwiftShell $ cd /
SwiftShell $ pwd
/

**Comment by hooman96** [comment]
can't reproduce it.

**Comment by JustinJiaDev** [comment]
Maybe I fixed it... Let me check it.

**Comment by JustinJiaDev** [comment]
Seems like it was Apple's bug and has been fixed.
