### ISSUE TITLE
Print Current Directory Name

### ISSUE THREAD

**Issue by JustinJiaDev** [JustinJiaDev/SwiftShell#4]
Replace `SwiftShell` with current directory name in `print(command: String, with arguments: [String]? = nil)`. e.g. Change from `SwiftShell $ cd ..` to `Documents $ cd ..` where `Documents` is current working directory name.

**Comment by hooman96** [comment]
isn't this already done?

```
Users/.../Documents $ cd ..
/Users/hooman $ pwd
/Users/hooman
```

**Comment by JustinJiaDev** [comment]
Yep. I implemented it.
