### ISSUE TITLE
Command Tab Completion

### ISSUE THREAD

**Issue by hooman96** [JustinJiaDev/SwiftShell#9]
Add the command tab completion on the playground if possible. 

Even in the case of options of commands. 

For example: `cd("Deskt(TAB)")`

**Comment by JustinJiaDev** [comment]
This is not possible. Xcode playground is only a [REPL](https://en.wikipedia.org/wiki/Read–eval–print_loop), which will automatically compile and run your code while typing.

Swift compiler is responsible for the code completion. 

We may be able to solve this issue in the future by making a custom Xcode plugin.
